#!/bin/bash
# vim: ft=sh:et:ts=4:sw=4:sts=4:

CWD=$(pwd)

usage() { echo "Usage: $0 [-v <1.6|2.0]" 1>&2; exit 1; }
while getopts ":v:" o; do
    case "${o}" in
        v)
            v=${OPTARG}
            [[ "$v" == "1.6" || "$v" == "2.0" ]] || usage
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${v}" ]; then
    usage
fi


rm -rf flapjack/opt/flapjack/Gemfile.lock
sed -i -e '4,6d' flapjack/opt/flapjack/Gemfile

if [ "$v" == "1.6" ];then
    sed -i '$a\gem "flapjack", "~> 1.6"' flapjack/opt/flapjack/Gemfile
    sed -i '2 s/2.0.0/1.6.0/' flapjack/DEBIAN/control
    cp init/flapjack-v1 flapjack/etc/init.d/flapjack
fi

if [ "$v" == "2.0" ];then
    sed -i '$a\gem "flapjack", "~> 2.0"' flapjack/opt/flapjack/Gemfile
    sed -i '$a\gem "toml"' flapjack/opt/flapjack/Gemfile
    sed -i '2 s/1.6.0/2.0.0/' flapjack/DEBIAN/control
    cp init/flapjack-v2 flapjack/etc/init.d/flapjack
fi

rm -rf flapjack/opt/flapjack/{vendor,.bundle,bin} || true
cd flapjack/opt/flapjack || exit 

bundle config build.eventmachine --with-cppflags=-I/usr/include/openssl
bundle install --without development --path vendor/bundle --binstubs bin || exit
VER=$(basename $(ls -d vendor/bundle/ruby/*/gems/flapjack-[0-9]*)|cut -f2 -d-)

cd "$CWD" || exit
cd flapjack/opt/flapjack/vendor/bundle/ruby/*/gems/flapjack-[0-9]* || exit

sed -i 's/json.event_queue_length/json.data.attributes.event_queue_length/' lib/flapjack/gateways/web/public/js/self_stats.js
if [[ "$v" == "2.0" ]];then
    sed -i "46i configure do\nset :mustermann_opts, { :type=>:regexp, :check_anchors=>false }\nend\n" lib/flapjack/gateways/jsonapi.rb
    sed -i -e '176s/*/"*"/' -e '184s/*/"*"/' -e '192s/*/"*"/' -e '199s/*/"*"/' -e '206s/*/"*"/' lib/flapjack/gateways/jsonapi.rb
fi

export GOPATH
GOPATH=$(pwd)
./build.sh
rm -rf src/*

cd "$CWD" || exit
cd flapjack || exit
find . -type f ! -regex '.*.git.*' ! -regex '.*?debian-binary.*' ! -regex '.*?DEBIAN.*' ! -regex '._.DS_Store' ! -regex '.DS_Store' -printf '%P ' | xargs md5sum > DEBIAN/md5sums

cd "$CWD" || exit
rm -rf flapjack/etc/init.d/*.v2
chmod 0755 flapjack/DEBIAN/{*rm,*inst}
fakeroot dpkg-deb -b flapjack flapjack_${VER}_all.deb
rm -rf flapjack/opt/flapjack/{vendor,.bundle,bin}
cd "$CWD" || exit
