#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	/etc/init.d/flapjack stop || kill -9 `cat /run/flapjack/flapjack.pid`
	gpasswd -d redis flapjack
	userdel flapjack || true
	update-rc.d flapjack remove >/dev/null
	rm -f /etc/redis/redis.conf
	dpkg-divert --rename --remove /etc/redis/redis.conf
	invoke-rc.d redis-server restart
	rm -rf /var/log/flapjack
	rm -f /etc/profile.d/flapjack.sh
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
